### ISSUE TITLE
Should timestamp be a part of the external ids of signed chains?

### ISSUE THREAD

**Issue by kirit93** [FactomProject/factom-harmony-connect-python-sdk#11]
While creating a signed chain, the timestamp of the signing is added to the external ids. Suppose I create a chain with Ext IDs - `['A', 'B', 'C']` and I sign it. Since the timestamp is added, I can keep creating chains with Ext IDs - `['A', 'B', 'C']` since each time it'll have a unique list of Ext IDs thanks to the timestamp.

I think the timestamp should be moved out of the Ext IDs and into the content of the first entry. This way I can't keep creating a chain with the same Ext IDs.

The Ext IDs should describe the chain, if I want to add an entry to a chain with Ext IDs - `['A', 'B', 'C']` - I could have potentially 100s of chains each with a different timestamp.

**Comment by Cahl-Dee** [comment]
The intended purpose of the timestamp in the External ID's is to act as a nonce, intentionally creating a new chain if, say, you wanted to create a chain with External IDs `['A', 'B', 'C']`, then later another user on the same blockchain wanted to create a chain with the External IDs `['A', 'B', 'C']`. 

As noted in #10, we intentionally reserved the entire Content field for customers to be able to submit data in any format they desired, without us adding additional metadata within it. This is vital for them, and others, to be able to validate the signatures at a later time (with or without the SDKs).

A user should not end up with 100s of duplicate chains unless there is an error in their code. When you create your chain, you should save the Chain ID, and create entries in that Chain ID view the create entries call.

**Comment by Cahl-Dee** [comment]
@kirit93 I believe this issue can be closed as well, based on the conclusion we reached in #10, correct?

**Comment by kirit93** [comment]
Correct.
