### ISSUE TITLE
Allow for **kwargs as the final argument for public methods as needed

### ISSUE THREAD

**Issue by dorono** [FactomProject/factom-harmony-connect-python-sdk#20]
This is simply to allow for optional settings in our methods in the future. 

By adding `**kwargs` as the final argument in any of these functions, we can reserve that space for any optional properties we could add, without having to worry about the order of any existing properties.  

So the task here to to move all optional arguments to go under the `**kwargs` object, and then pull those `**kwargs` properties out into the body of the method.

**Comment by hieumt2** [comment]
@dorono @sambarnes  please review PR #22 updated code for this issue
