### ISSUE TITLE
combine client-overrides changes with receipts and anchors 

### ISSUE THREAD

**Issue by dorono** [FactomProject/factom-harmony-connect-python-sdk#23]
There may be some issues incorporating @sambarnes's changes (he added Anchors and Receipts clients in PR https://github.com/FactomProject/factom-harmony-connect-python-sdk/pull/21), which are now part of master, and it is likely that there will be bugs that show up in the unit tests. We should confirm that all of the tests are passing now that we've added receipts and anchors.

Steps:
1) Rebase to master to get anchors and receipts code
2) Incorporate `**kwargs` and  the client override arguments  (that work has been done on the existing methods as part of https://github.com/FactomProject/factom-harmony-connect-python-sdk/pull/22) into the new methods as outlined in `factom_sdk/client/anchors_client.py` and `factom_sdk/client/receipts_client.py`
3) confirm that all unit tests are still working

**Comment by hieumt2** [comment]
- [x] Rebase to master to get anchors and receipts code
- [x] Incorporate **kwargs and the client override arguments (that work has been done on the existing methods as part of #22) into the new methods as outlined in 
- [x] Confirm that all unit tests are still working

**Comment by dorono** [comment]
Work has been completed in https://github.com/FactomProject/factom-harmony-connect-python-sdk/pull/22
